name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.FIREBASE_API }}"
      - name: Echo a secret  
        run: echo "your secret token is ${{ secrets.FIREBASE_API }}"
