name: Build and Deploy

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez pour déployer sur GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Inject Firebase API key
      run: echo "var firebaseConfig = { apiKey: '${{ secrets.FIREBASE_API }}', ... };" > assets/js/firebase.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # ou le répertoire de sortie de votre build
